### ISSUE TITLE
Core functionality for metadata repository

### ISSUE THREAD

**Issue by nawatts** [feltus/BDSS#62]
So far, there's still no way to order URLs by estimated transfer speed.

This will be done by using a rolling average of transfer speeds from past transfers from that data source.

To get that information, several things need to be done.
- [x] Data model to store timing reports in database (#53)
- [x] Data model to known test files in database (#47)
- [x] Actual data for some data sources, test files, and transforms (NCBI FTP and DTNs?)
- [x] A way for admins to run test transfers using those test files (#61)
